export { default as api211Routes } from './api211Routes.js';
export { default as availabilityRoutes } from './availabilityRoutes.js';
export { default as conditionRoutes } from './conditionRoutes.js';
export { default as communicationRoutes } from './communicationRoutes.js';
export { default as consentRoutes } from './consentRoutes.js';
export { default as emailRoutes } from './emailRoutes.js';
export { default as exclusionRoutes } from './exclusionRoutes.js';
export { default as fileuploadRoutes } from './fileuploadRoutes.js';
export { default as goalRoutes } from './goalRoutes.js';
export { default as organizationRoutes } from './organizationRoutes.js';
export { default as patientRoutes } from './patientRoutes.js';
export { default as practitionerRoutes } from './practitionerRoutes.js';
export { default as provenanceRoutes } from './provenanceRoutes.js';
export { default as roleRoutes } from './roleRoutes.js';
export { default as serverstatsRoutes } from './serverstatsRoutes.js';
export { default as serviceRequestRoutes } from './serviceRequestRoutes.js';
export { default as taskRoutes } from './taskRoutes.js';
export { default as activityDefinitionRoutes } from './activityDefinitionRoutes.js';
export { default as planDefinitionRoutes } from './planDefinitionRoutes.js';
export { default as timerRoutes } from './timerRoutes.js';
export { default as templateActivityRoutes } from './templateActivityRoutes.js';
export { default as templateEventRoutes } from './templateEventRoutes.js';
export { default as templatePlanRoutes } from './templatePlanRoutes.js';
export { default as inviteRoutes } from './inviteRoutes.js';
export { default as endpointRoutes } from './endpointRoutes.js';

export { default as testActivityRoutes} from './testActivityRoutes.js';
